# Generated by Django 4.1.5 on 2024-01-10 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_project_url_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url_project',
            new_name='link',
        ),
    ]
